services:
  facturador-monotributista-api:
    container_name: facturador-monotributista-api
    build: .
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_URL=postgresql://afip_user:afip_pass@postgres_afip:5432/afip_db
    networks:
      - afip_net

networks:
  afip_net:
    external: true
